/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'platform' : IDL.Text,
  'budget' : IDL.Nat,
  'engagement' : IDL.Nat,
  'reach' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const Time = IDL.Int;
export const LeadStage = IDL.Variant({
  'enrolled' : IDL.Null,
  'applied' : IDL.Null,
  'visa' : IDL.Null,
  'inquiry' : IDL.Null,
});
export const StudentLead = IDL.Record({
  'id' : IDL.Nat,
  'assignedTo' : IDL.Principal,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'stage' : LeadStage,
  'notes' : IDL.Text,
  'budget' : IDL.Nat,
});
export const SocialPost = IDL.Record({
  'id' : IDL.Nat,
  'publishDate' : Time,
  'contentPillar' : IDL.Text,
  'platform' : IDL.Text,
  'campaignName' : IDL.Text,
  'engagement' : IDL.Nat,
  'reach' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Principal,
  'dueDate' : Time,
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countActiveLeads' : IDL.Func([], [IDL.Nat], ['query']),
  'createCampaign' : IDL.Func([Campaign], [IDL.Nat], []),
  'createLead' : IDL.Func([StudentLead], [IDL.Nat], []),
  'createPost' : IDL.Func([SocialPost], [IDL.Nat], []),
  'createTask' : IDL.Func([Task], [IDL.Nat], []),
  'deleteCampaign' : IDL.Func([IDL.Nat], [], []),
  'deleteSocialPost' : IDL.Func([IDL.Nat], [], []),
  'deleteStudentLead' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(StudentLead)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(SocialPost)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [StudentLead], ['query']),
  'getLeadsAssignedToUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudentLead)],
      ['query'],
    ),
  'getLeadsByStage' : IDL.Func([LeadStage], [IDL.Vec(StudentLead)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [SocialPost], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksAssignedToUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getTotalEngagement' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalReach' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCampaign' : IDL.Func([IDL.Nat, Campaign], [], []),
  'updateSocialPost' : IDL.Func([IDL.Nat, SocialPost], [], []),
  'updateStudentLead' : IDL.Func([IDL.Nat, StudentLead], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'platform' : IDL.Text,
    'budget' : IDL.Nat,
    'engagement' : IDL.Nat,
    'reach' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const Time = IDL.Int;
  const LeadStage = IDL.Variant({
    'enrolled' : IDL.Null,
    'applied' : IDL.Null,
    'visa' : IDL.Null,
    'inquiry' : IDL.Null,
  });
  const StudentLead = IDL.Record({
    'id' : IDL.Nat,
    'assignedTo' : IDL.Principal,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'stage' : LeadStage,
    'notes' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const SocialPost = IDL.Record({
    'id' : IDL.Nat,
    'publishDate' : Time,
    'contentPillar' : IDL.Text,
    'platform' : IDL.Text,
    'campaignName' : IDL.Text,
    'engagement' : IDL.Nat,
    'reach' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Principal,
    'dueDate' : Time,
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countActiveLeads' : IDL.Func([], [IDL.Nat], ['query']),
    'createCampaign' : IDL.Func([Campaign], [IDL.Nat], []),
    'createLead' : IDL.Func([StudentLead], [IDL.Nat], []),
    'createPost' : IDL.Func([SocialPost], [IDL.Nat], []),
    'createTask' : IDL.Func([Task], [IDL.Nat], []),
    'deleteCampaign' : IDL.Func([IDL.Nat], [], []),
    'deleteSocialPost' : IDL.Func([IDL.Nat], [], []),
    'deleteStudentLead' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(StudentLead)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(SocialPost)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [StudentLead], ['query']),
    'getLeadsAssignedToUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudentLead)],
        ['query'],
      ),
    'getLeadsByStage' : IDL.Func(
        [LeadStage],
        [IDL.Vec(StudentLead)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [SocialPost], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksAssignedToUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTotalEngagement' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalReach' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCampaign' : IDL.Func([IDL.Nat, Campaign], [], []),
    'updateSocialPost' : IDL.Func([IDL.Nat, SocialPost], [], []),
    'updateStudentLead' : IDL.Func([IDL.Nat, StudentLead], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };