/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : bigint,
  'status' : string,
  'endDate' : string,
  'name' : string,
  'platform' : string,
  'budget' : bigint,
  'engagement' : bigint,
  'reach' : bigint,
  'startDate' : string,
}
export type LeadStage = { 'enrolled' : null } |
  { 'applied' : null } |
  { 'visa' : null } |
  { 'inquiry' : null };
export interface SocialPost {
  'id' : bigint,
  'publishDate' : Time,
  'contentPillar' : string,
  'platform' : string,
  'campaignName' : string,
  'engagement' : bigint,
  'reach' : bigint,
}
export interface StudentLead {
  'id' : bigint,
  'assignedTo' : Principal,
  'source' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'stage' : LeadStage,
  'notes' : string,
  'budget' : bigint,
}
export interface Task {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'assignedTo' : Principal,
  'dueDate' : Time,
  'priority' : string,
}
export type Time = bigint;
export interface UserProfile {
  'userId' : Principal,
  'role' : string,
  'fullName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countActiveLeads' : ActorMethod<[], bigint>,
  'createCampaign' : ActorMethod<[Campaign], bigint>,
  'createLead' : ActorMethod<[StudentLead], bigint>,
  'createPost' : ActorMethod<[SocialPost], bigint>,
  'createTask' : ActorMethod<[Task], bigint>,
  'deleteCampaign' : ActorMethod<[bigint], undefined>,
  'deleteSocialPost' : ActorMethod<[bigint], undefined>,
  'deleteStudentLead' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllLeads' : ActorMethod<[], Array<StudentLead>>,
  'getAllPosts' : ActorMethod<[], Array<SocialPost>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[bigint], [] | [Campaign]>,
  'getLead' : ActorMethod<[bigint], StudentLead>,
  'getLeadsAssignedToUser' : ActorMethod<[Principal], Array<StudentLead>>,
  'getLeadsByStage' : ActorMethod<[LeadStage], Array<StudentLead>>,
  'getPost' : ActorMethod<[bigint], SocialPost>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTasksAssignedToUser' : ActorMethod<[Principal], Array<Task>>,
  'getTotalEngagement' : ActorMethod<[], bigint>,
  'getTotalReach' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCampaign' : ActorMethod<[bigint, Campaign], undefined>,
  'updateSocialPost' : ActorMethod<[bigint, SocialPost], undefined>,
  'updateStudentLead' : ActorMethod<[bigint, StudentLead], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];